name: Bump Year

on:
    schedule:
        - cron: "0 0 1 1 *" # Jan 1, 00:00 UTC yearly
    workflow_dispatch:

jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Update year strings
              run: |
                  YEAR=$(date +%Y)
                  # LICENSE (replace "Copyright (c) YYYY")
                  if [ -f LICENSE ]; then
                    sed -i.bak -E "s/(Copyright \(c\) )20[0-9]{2}/\1${YEAR}/" LICENSE || true
                    rm -f LICENSE.bak
                  fi
                  # README footer year (optional)
                  if [ -f README.md ]; then
                    sed -i.bak -E "s/© 20[0-9]{2}/© ${YEAR}/" README.md || true
                    rm -f README.md.bak
                  fi

            - name: Commit & push if changed
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore: bump year"
                  file_pattern: |
                      LICENSE
                      README.md
